/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace IRollup {
  export type WithdrawalStruct = {
    recipient: PromiseOrValue<string>;
    tokenIndex: PromiseOrValue<BigNumberish>;
    amount: PromiseOrValue<BigNumberish>;
    salt: PromiseOrValue<BytesLike>;
  };

  export type WithdrawalStructOutput = [string, number, BigNumber, string] & {
    recipient: string;
    tokenIndex: number;
    amount: BigNumber;
    salt: string;
  };
}

export declare namespace ILiquidity {
  export type DepositStruct = {
    recipientSaltHash: PromiseOrValue<BytesLike>;
    tokenIndex: PromiseOrValue<BigNumberish>;
    amount: PromiseOrValue<BigNumberish>;
  };

  export type DepositStructOutput = [string, number, BigNumber] & {
    recipientSaltHash: string;
    tokenIndex: number;
    amount: BigNumber;
  };
}

export interface RollupInterface extends utils.Interface {
  functions: {
    "_blockBuilderRegistryContract()": FunctionFragment;
    "_liquidityContract()": FunctionFragment;
    "_scrollMessenger()": FunctionFragment;
    "getBlockHash(uint32)": FunctionFragment;
    "getDepositTreeRoot()": FunctionFragment;
    "getLastProcessedWithdrawalId()": FunctionFragment;
    "postBlock(bool,bytes32,uint128,bytes32,bytes32,uint256[2],uint256[4],uint256[4])": FunctionFragment;
    "postWithdrawalRequests((address,uint32,uint256,bytes32)[],uint256[],bytes)": FunctionFragment;
    "processDeposits((bytes32,uint32,uint256)[])": FunctionFragment;
    "submitBlockFraudProof(uint32,address,uint256[],bytes)": FunctionFragment;
    "submitWithdrawals(uint256)": FunctionFragment;
    "updateDependentContract(address,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "_blockBuilderRegistryContract"
      | "_liquidityContract"
      | "_scrollMessenger"
      | "getBlockHash"
      | "getDepositTreeRoot"
      | "getLastProcessedWithdrawalId"
      | "postBlock"
      | "postWithdrawalRequests"
      | "processDeposits"
      | "submitBlockFraudProof"
      | "submitWithdrawals"
      | "updateDependentContract"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "_blockBuilderRegistryContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_liquidityContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_scrollMessenger",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBlockHash",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositTreeRoot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLastProcessedWithdrawalId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "postBlock",
    values: [
      PromiseOrValue<boolean>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>
      ],
      [
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>
      ]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "postWithdrawalRequests",
    values: [
      IRollup.WithdrawalStruct[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "processDeposits",
    values: [ILiquidity.DepositStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "submitBlockFraudProof",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "submitWithdrawals",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDependentContract",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "_blockBuilderRegistryContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_liquidityContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_scrollMessenger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBlockHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepositTreeRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastProcessedWithdrawalId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "postBlock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "postWithdrawalRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processDeposits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitBlockFraudProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitWithdrawals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDependentContract",
    data: BytesLike
  ): Result;

  events: {
    "BlockFraudProofSubmitted(uint32,address,address)": EventFragment;
    "BlockPosted(bytes32,address,uint256,bytes32,bytes32)": EventFragment;
    "DepositsProcessed(bytes32)": EventFragment;
    "WithdrawRequested(bytes32,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BlockFraudProofSubmitted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BlockPosted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DepositsProcessed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawRequested"): EventFragment;
}

export interface BlockFraudProofSubmittedEventObject {
  blockNumber: number;
  blockBuilder: string;
  challenger: string;
}
export type BlockFraudProofSubmittedEvent = TypedEvent<
  [number, string, string],
  BlockFraudProofSubmittedEventObject
>;

export type BlockFraudProofSubmittedEventFilter =
  TypedEventFilter<BlockFraudProofSubmittedEvent>;

export interface BlockPostedEventObject {
  prevBlockHash: string;
  blockBuilder: string;
  blockNumber: BigNumber;
  depositTreeRoot: string;
  signatureHash: string;
}
export type BlockPostedEvent = TypedEvent<
  [string, string, BigNumber, string, string],
  BlockPostedEventObject
>;

export type BlockPostedEventFilter = TypedEventFilter<BlockPostedEvent>;

export interface DepositsProcessedEventObject {
  depositTreeRoot: string;
}
export type DepositsProcessedEvent = TypedEvent<
  [string],
  DepositsProcessedEventObject
>;

export type DepositsProcessedEventFilter =
  TypedEventFilter<DepositsProcessedEvent>;

export interface WithdrawRequestedEventObject {
  withdrawalRequest: string;
  withdrawAggregator: string;
}
export type WithdrawRequestedEvent = TypedEvent<
  [string, string],
  WithdrawRequestedEventObject
>;

export type WithdrawRequestedEventFilter =
  TypedEventFilter<WithdrawRequestedEvent>;

export interface Rollup extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RollupInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _blockBuilderRegistryContract(overrides?: CallOverrides): Promise<[string]>;

    _liquidityContract(overrides?: CallOverrides): Promise<[string]>;

    _scrollMessenger(overrides?: CallOverrides): Promise<[string]>;

    getBlockHash(
      blockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getDepositTreeRoot(overrides?: CallOverrides): Promise<[string]>;

    getLastProcessedWithdrawalId(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    postBlock(
      isRegistrationBlock: PromiseOrValue<boolean>,
      txTreeRoot: PromiseOrValue<BytesLike>,
      senderFlags: PromiseOrValue<BigNumberish>,
      publicKeysHash: PromiseOrValue<BytesLike>,
      accountIdsHash: PromiseOrValue<BytesLike>,
      aggregatedPublicKey: [
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>
      ],
      aggregatedSignature: [
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>
      ],
      messagePoint: [
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>
      ],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    postWithdrawalRequests(
      withdrawalRequests: IRollup.WithdrawalStruct[],
      publicInputs: PromiseOrValue<BigNumberish>[],
      proof: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    processDeposits(
      deposits: ILiquidity.DepositStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    submitBlockFraudProof(
      blockNumber: PromiseOrValue<BigNumberish>,
      blockBuilder: PromiseOrValue<string>,
      publicInputs: PromiseOrValue<BigNumberish>[],
      proof: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    submitWithdrawals(
      lastProcessedWithdrawId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateDependentContract(
      liquidityContract: PromiseOrValue<string>,
      blockBuilderRegistryContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  _blockBuilderRegistryContract(overrides?: CallOverrides): Promise<string>;

  _liquidityContract(overrides?: CallOverrides): Promise<string>;

  _scrollMessenger(overrides?: CallOverrides): Promise<string>;

  getBlockHash(
    blockNumber: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getDepositTreeRoot(overrides?: CallOverrides): Promise<string>;

  getLastProcessedWithdrawalId(overrides?: CallOverrides): Promise<BigNumber>;

  postBlock(
    isRegistrationBlock: PromiseOrValue<boolean>,
    txTreeRoot: PromiseOrValue<BytesLike>,
    senderFlags: PromiseOrValue<BigNumberish>,
    publicKeysHash: PromiseOrValue<BytesLike>,
    accountIdsHash: PromiseOrValue<BytesLike>,
    aggregatedPublicKey: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ],
    aggregatedSignature: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ],
    messagePoint: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  postWithdrawalRequests(
    withdrawalRequests: IRollup.WithdrawalStruct[],
    publicInputs: PromiseOrValue<BigNumberish>[],
    proof: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  processDeposits(
    deposits: ILiquidity.DepositStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  submitBlockFraudProof(
    blockNumber: PromiseOrValue<BigNumberish>,
    blockBuilder: PromiseOrValue<string>,
    publicInputs: PromiseOrValue<BigNumberish>[],
    proof: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  submitWithdrawals(
    lastProcessedWithdrawId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateDependentContract(
    liquidityContract: PromiseOrValue<string>,
    blockBuilderRegistryContract: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    _blockBuilderRegistryContract(overrides?: CallOverrides): Promise<string>;

    _liquidityContract(overrides?: CallOverrides): Promise<string>;

    _scrollMessenger(overrides?: CallOverrides): Promise<string>;

    getBlockHash(
      blockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getDepositTreeRoot(overrides?: CallOverrides): Promise<string>;

    getLastProcessedWithdrawalId(overrides?: CallOverrides): Promise<BigNumber>;

    postBlock(
      isRegistrationBlock: PromiseOrValue<boolean>,
      txTreeRoot: PromiseOrValue<BytesLike>,
      senderFlags: PromiseOrValue<BigNumberish>,
      publicKeysHash: PromiseOrValue<BytesLike>,
      accountIdsHash: PromiseOrValue<BytesLike>,
      aggregatedPublicKey: [
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>
      ],
      aggregatedSignature: [
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>
      ],
      messagePoint: [
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>
      ],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    postWithdrawalRequests(
      withdrawalRequests: IRollup.WithdrawalStruct[],
      publicInputs: PromiseOrValue<BigNumberish>[],
      proof: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    processDeposits(
      deposits: ILiquidity.DepositStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    submitBlockFraudProof(
      blockNumber: PromiseOrValue<BigNumberish>,
      blockBuilder: PromiseOrValue<string>,
      publicInputs: PromiseOrValue<BigNumberish>[],
      proof: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    submitWithdrawals(
      lastProcessedWithdrawId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateDependentContract(
      liquidityContract: PromiseOrValue<string>,
      blockBuilderRegistryContract: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "BlockFraudProofSubmitted(uint32,address,address)"(
      blockNumber?: PromiseOrValue<BigNumberish> | null,
      blockBuilder?: PromiseOrValue<string> | null,
      challenger?: PromiseOrValue<string> | null
    ): BlockFraudProofSubmittedEventFilter;
    BlockFraudProofSubmitted(
      blockNumber?: PromiseOrValue<BigNumberish> | null,
      blockBuilder?: PromiseOrValue<string> | null,
      challenger?: PromiseOrValue<string> | null
    ): BlockFraudProofSubmittedEventFilter;

    "BlockPosted(bytes32,address,uint256,bytes32,bytes32)"(
      prevBlockHash?: PromiseOrValue<BytesLike> | null,
      blockBuilder?: PromiseOrValue<string> | null,
      blockNumber?: null,
      depositTreeRoot?: null,
      signatureHash?: null
    ): BlockPostedEventFilter;
    BlockPosted(
      prevBlockHash?: PromiseOrValue<BytesLike> | null,
      blockBuilder?: PromiseOrValue<string> | null,
      blockNumber?: null,
      depositTreeRoot?: null,
      signatureHash?: null
    ): BlockPostedEventFilter;

    "DepositsProcessed(bytes32)"(
      depositTreeRoot?: null
    ): DepositsProcessedEventFilter;
    DepositsProcessed(depositTreeRoot?: null): DepositsProcessedEventFilter;

    "WithdrawRequested(bytes32,address)"(
      withdrawalRequest?: PromiseOrValue<BytesLike> | null,
      withdrawAggregator?: null
    ): WithdrawRequestedEventFilter;
    WithdrawRequested(
      withdrawalRequest?: PromiseOrValue<BytesLike> | null,
      withdrawAggregator?: null
    ): WithdrawRequestedEventFilter;
  };

  estimateGas: {
    _blockBuilderRegistryContract(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _liquidityContract(overrides?: CallOverrides): Promise<BigNumber>;

    _scrollMessenger(overrides?: CallOverrides): Promise<BigNumber>;

    getBlockHash(
      blockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDepositTreeRoot(overrides?: CallOverrides): Promise<BigNumber>;

    getLastProcessedWithdrawalId(overrides?: CallOverrides): Promise<BigNumber>;

    postBlock(
      isRegistrationBlock: PromiseOrValue<boolean>,
      txTreeRoot: PromiseOrValue<BytesLike>,
      senderFlags: PromiseOrValue<BigNumberish>,
      publicKeysHash: PromiseOrValue<BytesLike>,
      accountIdsHash: PromiseOrValue<BytesLike>,
      aggregatedPublicKey: [
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>
      ],
      aggregatedSignature: [
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>
      ],
      messagePoint: [
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>
      ],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    postWithdrawalRequests(
      withdrawalRequests: IRollup.WithdrawalStruct[],
      publicInputs: PromiseOrValue<BigNumberish>[],
      proof: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    processDeposits(
      deposits: ILiquidity.DepositStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    submitBlockFraudProof(
      blockNumber: PromiseOrValue<BigNumberish>,
      blockBuilder: PromiseOrValue<string>,
      publicInputs: PromiseOrValue<BigNumberish>[],
      proof: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    submitWithdrawals(
      lastProcessedWithdrawId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateDependentContract(
      liquidityContract: PromiseOrValue<string>,
      blockBuilderRegistryContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _blockBuilderRegistryContract(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _liquidityContract(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _scrollMessenger(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getBlockHash(
      blockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDepositTreeRoot(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLastProcessedWithdrawalId(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    postBlock(
      isRegistrationBlock: PromiseOrValue<boolean>,
      txTreeRoot: PromiseOrValue<BytesLike>,
      senderFlags: PromiseOrValue<BigNumberish>,
      publicKeysHash: PromiseOrValue<BytesLike>,
      accountIdsHash: PromiseOrValue<BytesLike>,
      aggregatedPublicKey: [
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>
      ],
      aggregatedSignature: [
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>
      ],
      messagePoint: [
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>
      ],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    postWithdrawalRequests(
      withdrawalRequests: IRollup.WithdrawalStruct[],
      publicInputs: PromiseOrValue<BigNumberish>[],
      proof: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    processDeposits(
      deposits: ILiquidity.DepositStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    submitBlockFraudProof(
      blockNumber: PromiseOrValue<BigNumberish>,
      blockBuilder: PromiseOrValue<string>,
      publicInputs: PromiseOrValue<BigNumberish>[],
      proof: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    submitWithdrawals(
      lastProcessedWithdrawId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateDependentContract(
      liquidityContract: PromiseOrValue<string>,
      blockBuilderRegistryContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
