/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  DepositContract,
  DepositContractInterface,
} from "../../../contracts/lib/DepositContract";

const _abi = [
  {
    inputs: [],
    name: "InvalidInitialization",
    type: "error",
  },
  {
    inputs: [],
    name: "MerkleTreeFull",
    type: "error",
  },
  {
    inputs: [],
    name: "NotInitializing",
    type: "error",
  },
  {
    inputs: [],
    name: "ReentrancyGuardReentrantCall",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint64",
        name: "version",
        type: "uint64",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    inputs: [],
    name: "depositCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getDepositRoot",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610288806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80632dfdf0b51461003b5780633ae0504714610059575b600080fd5b610043610077565b6040516100509190610187565b60405180910390f35b61006161007d565b60405161006e91906101bb565b60405180910390f35b60205481565b600061008761008c565b905090565b6000806021549050600060205490506000602154905060005b6020811015610164576001808285901c160361010057600081602081106100cf576100ce6101d6565b5b0154846040516020016100e3929190610226565b60405160208183030381529060405280519060200120935061012c565b8382604051602001610113929190610226565b6040516020818303038152906040528051906020012093505b818260405160200161013f929190610226565b60405160208183030381529060405280519060200120915080806001019150506100a5565b5082935050505090565b6000819050919050565b6101818161016e565b82525050565b600060208201905061019c6000830184610178565b92915050565b6000819050919050565b6101b5816101a2565b82525050565b60006020820190506101d060008301846101ac565b92915050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052603260045260246000fd5b6000819050919050565b61022061021b826101a2565b610205565b82525050565b6000610232828561020f565b602082019150610242828461020f565b602082019150819050939250505056fea2646970667358221220df74354945ed443d2b6afa3e317d0121795f1a310e79178e937c3f6169286eef64736f6c63430008180033";

type DepositContractConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DepositContractConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DepositContract__factory extends ContractFactory {
  constructor(...args: DepositContractConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      DepositContract & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): DepositContract__factory {
    return super.connect(runner) as DepositContract__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DepositContractInterface {
    return new Interface(_abi) as DepositContractInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): DepositContract {
    return new Contract(address, _abi, runner) as unknown as DepositContract;
  }
}
