/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface IRollupInterface extends utils.Interface {
  functions: {
    "getBlockHash(uint32)": FunctionFragment;
    "stopBlockBuilder()": FunctionFragment;
    "updateBlockBuilder(string)": FunctionFragment;
    "updateDepositRoot(bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getBlockHash"
      | "stopBlockBuilder"
      | "updateBlockBuilder"
      | "updateDepositRoot"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getBlockHash",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "stopBlockBuilder",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateBlockBuilder",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDepositRoot",
    values: [PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(
    functionFragment: "getBlockHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stopBlockBuilder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateBlockBuilder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDepositRoot",
    data: BytesLike
  ): Result;

  events: {
    "BlockBuilderUpdated(address,string,uint256)": EventFragment;
    "BlockPosted(bytes32,address,uint256,bytes32,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BlockBuilderUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BlockPosted"): EventFragment;
}

export interface BlockBuilderUpdatedEventObject {
  blockBuilder: string;
  url: string;
  stakeAmount: BigNumber;
}
export type BlockBuilderUpdatedEvent = TypedEvent<
  [string, string, BigNumber],
  BlockBuilderUpdatedEventObject
>;

export type BlockBuilderUpdatedEventFilter =
  TypedEventFilter<BlockBuilderUpdatedEvent>;

export interface BlockPostedEventObject {
  prevBlockHash: string;
  blockBuilder: string;
  blockNumber: BigNumber;
  blockContentHash: string;
  depositRoot: string;
}
export type BlockPostedEvent = TypedEvent<
  [string, string, BigNumber, string, string],
  BlockPostedEventObject
>;

export type BlockPostedEventFilter = TypedEventFilter<BlockPostedEvent>;

export interface IRollup extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IRollupInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getBlockHash(
      blockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    stopBlockBuilder(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateBlockBuilder(
      url: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateDepositRoot(
      depositRoot: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  getBlockHash(
    blockNumber: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  stopBlockBuilder(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateBlockBuilder(
    url: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateDepositRoot(
    depositRoot: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getBlockHash(
      blockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    stopBlockBuilder(overrides?: CallOverrides): Promise<void>;

    updateBlockBuilder(
      url: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateDepositRoot(
      depositRoot: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "BlockBuilderUpdated(address,string,uint256)"(
      blockBuilder?: PromiseOrValue<string> | null,
      url?: null,
      stakeAmount?: null
    ): BlockBuilderUpdatedEventFilter;
    BlockBuilderUpdated(
      blockBuilder?: PromiseOrValue<string> | null,
      url?: null,
      stakeAmount?: null
    ): BlockBuilderUpdatedEventFilter;

    "BlockPosted(bytes32,address,uint256,bytes32,bytes32)"(
      prevBlockHash?: PromiseOrValue<BytesLike> | null,
      blockBuilder?: PromiseOrValue<string> | null,
      blockNumber?: null,
      blockContentHash?: null,
      depositRoot?: null
    ): BlockPostedEventFilter;
    BlockPosted(
      prevBlockHash?: PromiseOrValue<BytesLike> | null,
      blockBuilder?: PromiseOrValue<string> | null,
      blockNumber?: null,
      blockContentHash?: null,
      depositRoot?: null
    ): BlockPostedEventFilter;
  };

  estimateGas: {
    getBlockHash(
      blockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    stopBlockBuilder(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateBlockBuilder(
      url: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateDepositRoot(
      depositRoot: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getBlockHash(
      blockNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    stopBlockBuilder(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateBlockBuilder(
      url: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateDepositRoot(
      depositRoot: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
