/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBlockBuilderRegistry } from "./IBlockBuilderRegistry";
export type { IRollup } from "./IRollup";
