/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IL1GasPriceOracle,
  IL1GasPriceOracleInterface,
} from "../../contracts/IL1GasPriceOracle";

const _abi = [
  {
    inputs: [],
    name: "l1BaseFee",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IL1GasPriceOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IL1GasPriceOracleInterface {
    return new utils.Interface(_abi) as IL1GasPriceOracleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IL1GasPriceOracle {
    return new Contract(address, _abi, signerOrProvider) as IL1GasPriceOracle;
  }
}
